#!/bin/zsh
# Compile rules.peep into a sourceable zsh fragment that
# peephole_optimize can call. The output script defines a function
# peephole_apply_rules that takes the lookahead context and returns
# whether to skip the current line.
#
# Usage: zsh tools/gen_peephole.sh > tools/peephole/rules_generated.sh
#
# Note [PeepholeDSL]
#   Rule grammar (one per line, leading 'rule' keyword):
#     rule NAME match 'regex' [followed_by 'regex'] [equal_groups M N] action drop
#
#   Each compiled rule reads two zsh-globals:
#     $cur       the current line
#     $lookahead the next non-blank line (may be empty if at EOF)
#   plus the regex match array provided by [[ "$cur" =~ ... ]].
#
#   On a match, the rule emits "skip=1" by setting that variable in
#   the caller's scope (peephole_optimize sees it). Each rule is
#   gated by opt_bisect_check using its NAME.

set -euo pipefail

SCRIPT_DIR="${0:A:h}"
RULES_FILE="${SCRIPT_DIR}/peephole/rules.peep"

if [[ ! -f "$RULES_FILE" ]]; then
  echo "ERROR: $RULES_FILE not found" >&2
  exit 1
fi

emit() { print -r -- "$1"; }

emit "# AUTOGENERATED FROM tools/peephole/rules.peep -- DO NOT EDIT BY HAND"
emit "# To regenerate: zsh tools/gen_peephole.sh > tools/peephole/rules_generated.sh"
emit ""
emit "# Each rule is gated by opt_bisect_check; sets skip=1 to drop the current line."
emit "peephole_apply_rules() {"

while IFS= read -r line; do
  # Strip comments and blank lines
  line="${line%%#*}"
  line="${line## }"
  line="${line%% }"
  [[ -z "$line" ]] && continue

  # Parse: rule NAME match 'regex' [followed_by 'regex'] [equal_groups M N] action drop
  if [[ ! "$line" =~ '^rule[[:space:]]+([A-Za-z_][A-Za-z0-9_]*)[[:space:]]+match[[:space:]]+(.+)[[:space:]]+action[[:space:]]+drop[[:space:]]*$' ]]; then
    echo "ERROR: malformed rule: $line" >&2
    exit 1
  fi
  name="${match[1]}"
  rest="${match[2]}"

  # Extract the leading single-quoted regex from rest
  if [[ "$rest" =~ ^\'([^\']*)\'(.*)$ ]]; then
    pattern_re="${match[1]}"
    rest="${match[2]##[[:space:]]##}"
  else
    echo "ERROR: rule $name: missing 'regex' after 'match'" >&2
    exit 1
  fi

  followed_by_re=""
  equal_g1=""
  equal_g2=""

  while [[ -n "$rest" ]]; do
    rest="${rest## }"
    if [[ "$rest" =~ ^followed_by[[:space:]]+\'([^\']*)\'(.*)$ ]]; then
      followed_by_re="${match[1]}"
      rest="${match[2]## }"
    elif [[ "$rest" =~ ^equal_groups[[:space:]]+([0-9]+)[[:space:]]+([0-9]+)(.*)$ ]]; then
      equal_g1="${match[1]}"
      equal_g2="${match[2]}"
      rest="${match[3]## }"
    elif [[ -z "$rest" ]]; then
      break
    else
      echo "ERROR: rule $name: unparsed clause: $rest" >&2
      exit 1
    fi
  done

  emit "  # Rule: $name"
  emit "  if (( ! skip )) && [[ \"\$cur\" =~ '$pattern_re' ]]; then"
  if [[ -n "$equal_g1" && -n "$equal_g2" ]]; then
    emit "    if [[ \"\${match[$equal_g1]}\" == \"\${match[$equal_g2]}\" ]]; then"
    emit "      opt_bisect_check 'peephole_$name' && skip=1"
    emit "    fi"
  elif [[ -n "$followed_by_re" ]]; then
    # Substitute \1 with the first capture group of the cur match.
    # Use a placeholder that will not collide with regex chars.
    rewritten_re="${followed_by_re//\\1/__INTERCAL_GROUP_1__}"
    emit "    local _g1=\"\${match[1]}\""
    emit "    local _expected=\"${rewritten_re//__INTERCAL_GROUP_1__/\$_g1}\""
    emit "    if [[ \"\$lookahead\" =~ \"\$_expected\" ]]; then"
    emit "      opt_bisect_check 'peephole_$name' && skip=1"
    emit "    fi"
  else
    emit "    opt_bisect_check 'peephole_$name' && skip=1"
  fi
  emit "  fi"
  emit ""
done < "$RULES_FILE"

emit "}"
