# AUTOGENERATED FROM tools/peephole/rules.peep -- DO NOT EDIT BY HAND
# To regenerate: zsh tools/gen_peephole.sh > tools/peephole/rules_generated.sh

# Each rule is gated by opt_bisect_check; sets skip=1 to drop the current line.
peephole_apply_rules() {
  # Rule: branch_to_next
  if (( ! skip )) && [[ "$cur" =~ '^[[:space:]]+b[[:space:]]+(_[a-zA-Z0-9_]+)[[:space:]]*$' ]]; then
    local _g1="${match[1]}"
    local _expected="^$_g1:"
    if [[ "$lookahead" =~ "$_expected" ]]; then
      opt_bisect_check 'peephole_branch_to_next' && skip=1
    fi
  fi

  # Rule: jmp_to_next
  if (( ! skip )) && [[ "$cur" =~ '^[[:space:]]+jmp[[:space:]]+(_[a-zA-Z0-9_]+)[[:space:]]*$' ]]; then
    local _g1="${match[1]}"
    local _expected="^$_g1:"
    if [[ "$lookahead" =~ "$_expected" ]]; then
      opt_bisect_check 'peephole_jmp_to_next' && skip=1
    fi
  fi

  # Rule: identity_mov
  if (( ! skip )) && [[ "$cur" =~ '^[[:space:]]+mov[[:space:]]+([wxer][a-z0-9]+|al|ax|eax|rax|cx|ecx|rcx|dx|edx|rdx),[[:space:]]*([wxer][a-z0-9]+|al|ax|eax|rax|cx|ecx|rcx|dx|edx|rdx)[[:space:]]*$' ]]; then
    if [[ "${match[1]}" == "${match[2]}" ]]; then
      opt_bisect_check 'peephole_identity_mov' && skip=1
    fi
  fi

}
